language: cpp
dist: bionic
os: linux
compiler: g++
group: travis_latest
addons:
  ssh_known_hosts: local.timschneeberger.me
env:
  global:
  - base_version: 1.3
  - secure: vgkrromcvPh3K23BBzMmE4H6kiYpoMOA/1kaofsbw7Vm/3DaU7BXI779Xyxi/vUgz+NvoRxoCD3arXE/hgTFKfhMq4NbvOIgak4cMCgogHTZ0aTM72HgXxxuYpr1E36LBcbd29TKbdYE2dtgHfe4zSmEvIuG8JSRpexhH4pcxaIZfJUY3QxfWEh72iqUK2cQ31qC+x2N6MCSUzImAEv8KlhxIuRAyoHn/VOqaZDkq8kZ6TwSfW8WU7H96va/RNMRuwLvKTF8t7wEOUs7rrUqg5m3KTTfR32E2bC4jez2/VAsIURyUW0jmerpMiK6jzDMsGi8VsVSO99dLyIcGCFTVqGkMgm6YHkRYWpGqGwqA+O6Qm8DsZyXEPIkcwazAPrO/fp8HMMbIKf7DXbc2JGq8g+hOVmNQgO+n6LLzs9ioPtQt09qWzEFIiMzDxp3H/RANsqFtqjodZeAY3zzEPY+jZ8IVYm67pAnuurj6o8syo6u7b7dKQwbXi4VB0g1BmOiwKreHKo6hgqhGCzw2xtzC4/+Rpws35cpvbPhBoMl2CypRtC2xHKhYIkheZjdr5aBSjGCotoFUqEfFJjOoLsxfJnysi3434hTCHRFgjQvw84nI4PHnDEkJk5LIEY+q9HxVozsvzkuffyZmmSIy/luQGWTw11nL6NoigGHFkOSmAc=
before_install:
- sudo apt-get update -qq
- sudo apt-get install lftp
- sudo apt-get install qtbase5-dev qt5-default qttools5-dev-tools
script:
- qmake -project
- qmake DDCToolbox.pro
- make
- touch DDCToolbox
- chmod +x build_deb_package.sh
- "./build_deb_package.sh"
after_success:
- for file in ./*.deb; do if [ -f "$file" ]; then export artifact=$file; break 1;
  fi; done;
- echo $artifact
- lftp -u pi,${SFTP_PWD} -e "set sftp:auto-confirm true;set ssl:check-hostname false;set
  ssl:verify-certificate false;put $artifact;quit" sftp://local.timschneeberger.me/disks/sandisk/www/nightly/ddctoolbox-debian/
